// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "googleApiKey": string;
      "source.crossref": boolean;
      "source.openLibrary": boolean;
      "source.googleBooks": boolean;
      "source.dnb": boolean;
      "source.semanticScholar": boolean;
      "previewMode": string;
      "dnbLanguage": string;
      "matchThreshold": number;
    };
  }
}
